<?php

namespace CloudFinance\EFattureWsClient\V1\Invoice;

class FSM10Map {

    public static function get()
    {
        return self::$map;
    }

    private static $map = [
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/DatiTrasmissione/IdTrasmittente/IdPaese",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/DatiTrasmissione/IdTrasmittente/IdCodice",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/DatiTrasmissione/ProgressivoInvio",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/DatiTrasmissione/FormatoTrasmissione",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/DatiTrasmissione/CodiceDestinatario",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/DatiTrasmissione/PECDestinatario",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/IdFiscaleIVA/IdPaese",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/IdFiscaleIVA/IdCodice",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/CodiceFiscale",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/Denominazione",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/Nome",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/Cognome",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/Sede/Indirizzo",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/Sede/NumeroCivico",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/Sede/CAP",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/Sede/Comune",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/Sede/Provincia",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/Sede/Nazione",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/StabileOrganizzazione/Indirizzo",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/StabileOrganizzazione/NumeroCivico",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/StabileOrganizzazione/CAP",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/StabileOrganizzazione/Comune",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/StabileOrganizzazione/Provincia",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/StabileOrganizzazione/Nazione",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/RappresentanteFiscale/IdFiscaleIVA/IdPaese",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/RappresentanteFiscale/IdFiscaleIVA/IdCodice",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/RappresentanteFiscale/Denominazione",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/RappresentanteFiscale/Nome",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/RappresentanteFiscale/Cognome",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/IscrizioneREA/Ufficio",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/IscrizioneREA/NumeroREA",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/IscrizioneREA/CapitaleSociale",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/IscrizioneREA/SocioUnico",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/IscrizioneREA/StatoLiquidazione",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CedentePrestatore/RegimeFiscale",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/IdentificativiFiscali/IdFiscaleIVA/IdPaese",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/IdentificativiFiscali/IdFiscaleIVA/IdCodice",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/IdentificativiFiscali/CodiceFiscale",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/Denominazione",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/Nome",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/Cognome",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/Sede/Indirizzo",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/Sede/NumeroCivico",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/Sede/CAP",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/Sede/Comune",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/Sede/Provincia",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/Sede/Nazione",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/StabileOrganizzazione/Indirizzo",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/StabileOrganizzazione/NumeroCivico",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/StabileOrganizzazione/CAP",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/StabileOrganizzazione/Comune",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/StabileOrganizzazione/Provincia",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/StabileOrganizzazione/Nazione",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/RappresentanteFiscale/IdFiscaleIVA/IdPaese",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/RappresentanteFiscale/IdFiscaleIVA/IdCodice",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/RappresentanteFiscale/Denominazione",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/RappresentanteFiscale/Nome",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/CessionarioCommittente/AltriDatiIdentificativi/RappresentanteFiscale/Cognome",
        "FatturaElettronicaSemplificata/FatturaElettronicaHeader/SoggettoEmittente",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiGenerali/DatiGeneraliDocumento/TipoDocumento",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiGenerali/DatiGeneraliDocumento/Divisa",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiGenerali/DatiGeneraliDocumento/Data",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiGenerali/DatiGeneraliDocumento/Numero",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiGenerali/DatiFatturaRettificata/NumeroFR",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiGenerali/DatiFatturaRettificata/DataFR",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiGenerali/DatiFatturaRettificata/ElementiRettificati",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiBeniServizi[n]/Descrizione",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiBeniServizi[n]/Importo",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiBeniServizi[n]/DatiIVA/Imposta",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiBeniServizi[n]/DatiIVA/Aliquota",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiBeniServizi[n]/Natura",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/DatiBeniServizi[n]/RiferimentoNormativo",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/Allegati[n]/NomeAttachment",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/Allegati[n]/AlgoritmoCompressione",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/Allegati[n]/FormatoAttachment",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/Allegati[n]/DescrizioneAttachment",
        "FatturaElettronicaSemplificata/FatturaElettronicaBody[n]/Allegati[n]/Attachment",
    ];

}